platform :ios, '16.0'

require_relative '../node_modules/react-native/scripts/react_native_pods'

install! 'cocoapods', :deterministic_uuids => false

target 'Medinet' do
  use_frameworks! :linkage => :static

  use_react_native!(
    :path => '../node_modules/react-native',
    :hermes_enabled => true,
    :fabric_enabled => true,
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  target 'MedinetTests' do
    inherit! :complete
  end

post_install do |installer|
  react_native_post_install(installer)

  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = 'arm64'
      config.build_settings['CLANG_CXX_LANGUAGE_STANDARD'] = 'c++17'
      config.build_settings['CLANG_CXX_LIBRARY'] = 'libc++'
      config.build_settings['OTHER_CPLUSPLUSFLAGS'] ||= ['$(inherited)', '-DFMT_EXPLICIT_CHAR8_T=0']
    end
  end
end
end